import type { NextPage } from 'next';
import Head from 'next/head';
import Game from '~components/game';

const Home: NextPage = () => (
	<div>
		<Head>
			<title>Twenty five game</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/public/favicon.ico" />
		</Head>

		<Game />
	</div>
);

export default Home;
